# Generated by Django 4.2.30 on 2026-04-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_transcriptentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('drop_pending', 'Drop Pending')], default='pending', max_length=20),
        ),
    ]
