# Generated by Django 4.2.30 on 2026-04-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('ta', 'Teaching Assistant'), ('professor', 'Professor'), ('advisor', 'Advisor'), ('registrar', 'Registrar'), ('sysadmin', 'System Admin')], max_length=20),
        ),
    ]
