from django.urls import path
from .views import (
    student_dashboard,
    course_catalog,
    my_courses,
    student_grades,
    student_course_detail,
    enrollment_history,
    student_detail,
    drop_enrollment,
    student_drop_enrollment,
    registrar_students,
    registrar_student_enrollment,
    propose_enrollment_add,
    propose_enrollment_remove,
    review_enrollment_change,
    add_transcript_entry,
    delete_transcript_entry,
    ta_dashboard,
    ta_course_grades,
    professor_dashboard,
    professor_course_grades,
    advisor_dashboard,
    registrar_dashboard,
    sysadmin_dashboard,
    rbac_policies,
    users_list,
    propose_enrollment,
    approve_enrollment,
    approve_drop,
    deny_drop,
    deny_enrollment,
    create_course,
    edit_course,
    delete_course,
    create_user,
    edit_user,
    delete_user,
    create_major,
)

urlpatterns = [
    path("student/", student_dashboard, name="student_dashboard"),
    path("student/catalog/", course_catalog, name="course_catalog"),
    path("student/my-courses/", my_courses, name="my_courses"),
    path("student/enrollment-history/", enrollment_history, name="enrollment_history"),
    path("student/grades/", student_grades, name="student_grades"),
    path("student/courses/<int:enrollment_id>/", student_course_detail, name="student_course_detail"),
    path("ta/", ta_dashboard, name="ta_dashboard"),
    path("ta/courses/<int:course_id>/grades/", ta_course_grades, name="ta_course_grades"),
    path("professor/", professor_dashboard, name="professor_dashboard"),
    path("professor/courses/<int:course_id>/grades/", professor_course_grades, name="professor_course_grades"),
    path("advisor/", advisor_dashboard, name="advisor_dashboard"),
    path("registrar/", registrar_dashboard, name="registrar_dashboard"),
    path("sysadmin/", sysadmin_dashboard, name="sysadmin_dashboard"),

    path("advisor/students/<int:student_id>/", student_detail, name="student_detail"),
    path("advisor/enrollments/<int:enrollment_id>/drop/", drop_enrollment, name="drop_enrollment"),
    path("enroll/<int:course_id>/", propose_enrollment, name="propose_enrollment"),
    path("approve/<int:enrollment_id>/", approve_enrollment, name="approve_enrollment"),
    path("deny/<int:enrollment_id>/", deny_enrollment, name="deny_enrollment"),
    path("drop/<int:enrollment_id>/", student_drop_enrollment, name="student_drop_enrollment"),
    path("drop/<int:enrollment_id>/approve/", approve_drop, name="approve_drop"),
    path("drop/<int:enrollment_id>/deny/", deny_drop, name="deny_drop"),

    path("courses/new/", create_course, name="create_course"),
    path("courses/<int:course_id>/edit/", edit_course, name="edit_course"),
    path("courses/<int:course_id>/delete/", delete_course, name="delete_course"),

    path("rbac-policies/", rbac_policies, name="rbac_policies"),
    path("registrar/students/", registrar_students, name="registrar_students"),
    path("registrar/students/<int:student_id>/", registrar_student_enrollment, name="registrar_student_enrollment"),
    path("registrar/students/<int:student_id>/add/", propose_enrollment_add, name="propose_enrollment_add"),
    path("registrar/students/<int:student_id>/remove/", propose_enrollment_remove, name="propose_enrollment_remove"),
    path("advisor/changes/<int:change_id>/review/", review_enrollment_change, name="review_enrollment_change"),
    path("registrar/students/<int:student_id>/transcript/add/", add_transcript_entry, name="add_transcript_entry"),
    path("registrar/students/<int:student_id>/transcript/<int:entry_id>/delete/", delete_transcript_entry, name="delete_transcript_entry"),
    path("users/", users_list, name="users_list"),
    path("users/new/", create_user, name="create_user"),
    path("users/<int:user_id>/edit/", edit_user, name="edit_user"),
    path("users/<int:user_id>/delete/", delete_user, name="delete_user"),
    path("students/new/", create_user, name="create_student"),
    path("majors/new/", create_major, name="create_major"),
]